version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: bert
      POSTGRES_USER: bert
      POSTGRES_PASSWORD: bert123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api-gateway:
    build: ./services/api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://bert:bert123@postgres:5432/bert
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  r-service:
    build: ./services/r-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  julia-service:
    build: ./services/julia-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production

  auth-service:
    build: ./services/auth-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=bert-super-secret-key-2024

  ai-service:
    build: ./services/ai-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production

  plugin-manager:
    build: ./services/plugin-manager
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production

  python-service:
    build: ./services/python-service
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production

volumes:
  postgres_data: